name: Changeset Check

on:
    pull_request:
        branches:
            - main

jobs:
    check-for-changeset:
        name: Check for Changeset
        runs-on: ubuntu-latest
        # Skip this check if the PR is from the changeset release PR
        if: "!contains(github.head_ref, 'changeset-release')"
        steps:
            - uses: actions/checkout@v4

            - name: Check for Changeset
              run: |
                  # Get all changed files in this PR
                  git fetch origin main
                  CHANGED_FILES=$(git diff --name-only origin/main HEAD)

                  # Check if any source files were changed
                  if echo "$CHANGED_FILES" | grep -q -E '\.rs$|\.ts$|package\.json'; then
                    # Check if a changeset was added
                    if ! echo "$CHANGED_FILES" | grep -q -E '\.changeset/.*\.md$' && [ ! -f .changeset/README.md ]; then
                      echo "Error: No changeset found. Please run 'pnpm changeset' to create one."
                      exit 1
                    fi
                  fi
